version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  frontend:
    container_name: frontend
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - 5173:5173
